### PR TITLE
Use goog.object/get instead of aget

### PR DESCRIPTION
**Pull request by mfikes**

### CODE REVIEW

**Comment by glittershark** [comment]
What does this get us?

**Comment by mfikes** [comment]
@glittershark It is only a quirk of implementation that `aget` works on objects. I suspect nothing is likely to break without the change. In the future, the use of `aget` on non-arrays will likely cause a ClojureScript compiler warning to be emitted.

**Comment by glittershark** [comment]
Oh, huh, TIL. Is that documented somewhere?

**Comment by glittershark** [comment]
If it's going to be a compiler warning soon I'm expecting just a mailing list thread or JIRA issue or something like that.

**Comment by mfikes** [comment]
@glittershark Not formally documented, AFAIK. Mentioned here https://clojurians-log.clojureverse.org/clojurescript/2015-07-31.html#inst-2015-07-31T00:52:48.004138Z
Recently created JIRA: https://dev.clojure.org/jira/browse/CLJS-2148

**Comment by glittershark** [comment]
Good enough for me

**Pull request merged**
